import { Slide, ToastContainer, Zoom } from "react-toastify";
import Navbar from "./components/Navbar";
import "./globals.css";
import { Providers } from "@/app/redux/Provider";
import "react-toastify/dist/ReactToastify.css";
export const metadata = {
  title: "Amazon 2.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Navbar />
          {children}
          <ToastContainer
            autoClose={1000}
            position="bottom-right"
            theme="colored"
          />
        </body>
      </Providers>
    </html>
  );
}
